
CREATE TABLE ALIMENTO
(
    COD_ALIMENTO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME VARCHAR(30) NOT NULL,
    DESC_ALIMENTO VARCHAR(70),
    QUANT_ALIMENTO SMALLINT NOT NULL,
    COD_AQUARIO INTEGER
);

CREATE TABLE AQUARIO
(
    COD_AQUARIO INTEGER PRIMARY KEY AUTOINCREMENT,
    TEMP_IDEAL SMALLINT NOT NULL,
    PERIODO INT NOT NULL,
    ULTIMO_ALIMENTO DATETIME DEFAULT NULL,
    COD_ALIMENTO INTEGER,
    FOREIGN KEY (COD_ALIMENTO)
       REFERENCES ALIMENTO(COD_ALIMENTO)

);

CREATE TABLE TEMPERATURA
(
    HORARIO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TEMP INT NOT NULL,
    COD_AQUARIO INT NOT NULL,
    FOREIGN KEY (COD_AQUARIO)
       REFERENCES AQUARIO(COD_AQUARIO)
);

INSERT INTO ALIMENTO  (NOME,DESC_ALIMENTO,QUANT_ALIMENTO)
VALUES
    ('AQUARIUM', 'PARA PEIXES FRAGEIS E PEQUENOS. AUMENTA A IMUNIDADE E EVITA VERMES', 10),
    ('GRANULES', 'GRÂNULOS COM VITAMINAS E MINERAIS', 15),
    ('GOLDFISH', 'RAÇÃO EXTRUSADA QUE REALÇA A COLORAÇÃO DE KINGUIOS E CARPAS', 20);


INSERT INTO AQUARIO
    (TEMP_IDEAL,PERIODO,COD_ALIMENTO)
VALUES
    (23, 1, 1),
    (21, 2, 2),
    (23, 6, 3),
    (20, 4, 2),
    (20, 8, 3);
INSERT INTO TEMPERATURA
    (TEMP,COD_AQUARIO)
VALUES
    (22, 2),
    (23, 3),
    (21, 4),
    (23, 3),
    (23, 1),
    (23, 1),
    (22, 2),
    (23, 5),
    (23, 4),
    (22, 4),
    (23, 5);
