-- SELECIONAR AQUARIO COM TEMPERATURAS ACIMA DE 30 E QUE A TEMPERATURA IDEAL SEJA ABAIXO DE 30 EM ORDEM DECRESCENTE DO AQUARIO
SELECT A.COD_AQUARIO, B.TEMP
FROM AQUARIO A JOIN TEMPERATURA B ON A.COD_AQUARIO = B.COD_AQUARIO
WHERE B.TEMP > A.TEMP_IDEAL AND B.COD_AQUARIO = A.COD_AQUARIO
ORDER BY 1

-- QUANTIDADE DE AQUARIOS QUE USA UM ALIMENTO
SELECT COD_AQUARIO , COUNT(COD_ALIMENTO) AS NUM
FROM AQUARIO
GROUP BY COD_AQUARIO

-- SELECIONA NA TABELA DE TEMPERATURA AS TEMPERATURAS ACIMA DA TEMPERATURA IDEAL
SELECT A.COD_AQUARIO, HORARIO, TEMP
FROM TEMPERATURA T JOIN AQUARIO A ON  A.COD_AQUARIO = T.COD_AQUARIO
WHERE  T.TEMP  > A.TEMP_IDEAL
ORDER BY 1;

-- EXIBE O RELATÓRIO DA TEMPERATURA ABAIXO DA TEMPERATURA IDEAL ENTRE OS DIAS ESPECIFICADOS
SELECT HORARIO, TEMP
FROM (
SELECT HORARIO, TEMP
    FROM TEMPERATURA T
        JOIN AQUARIO A ON  A.COD_AQUARIO = T.COD_AQUARIO
    WHERE  T.TEMP  < A.TEMP_IDEAL) A
WHERE HORARIO BETWEEN '2020-11-29 22:32:39.517' AND '2020-11-30 22:52:59.517'

-- SELECIONAR OS ALIMENTOS E A QUANTIDADE EM CADA AQUARIO EM ORDEM CRESCENTE DO AQUARIO
SELECT B.COD_AQUARIO, A.NOME, A.QUANT_ALIMENTO
FROM ALIMENTO A JOIN AQUARIO B ON A.COD_ALIMENTO = B.COD_AQUARIO
ORDER BY 1

-- SELECIONA NA TABELA DE TEMPERATURA AS TEMPERATURAS ABAIXO DA TEMPERATURA IDEAL
SELECT A.COD_AQUARIO, HORARIO, TEMP
FROM TEMPERATURA  T
    JOIN AQUARIO A ON  A.COD_AQUARIO = T.COD_AQUARIO
WHERE  T.TEMP < A.TEMP_IDEAL
ORDER BY 1;

--SELECIONA A DATA DA ULTIMA ALIMENTAÇÃO DE TODOS OS AQUARIOS
SELECT COD_AQUARIO, ULTIMO_ALIMENTO
FROM AQUARIO

-- RELATORIO DE TEMPERATURA ENTRE UM PERIODO
SELECT HORARIO, TEMP
FROM TEMPERATURA
WHERE HORARIO BETWEEN '2020-11-29 22:32:39.517' AND '2020-11-30 22:52:59.517'

-- ENCONTRA DETERMINADO ALIMENTO PELA SUA DESCRIÇÃO E CÓDIGO AGUÁRIO
SELECT B.COD_AQUARIO, A.NOME, A.DESC_ALIMENTO
FROM ALIMENTO A JOIN AQUARIO B ON A.COD_ALIMENTO = B.COD_AQUARIO
WHERE DESC_ALIMENTO = 'GRÂNULOS COM VITAMINAS E MINERAIS' AND COD_AQUARIO = 1

-- RETORNA O NOME E DESCRIÇÃO DO ALIMENTO PRESENTE NO AQUARIO
SELECT B.COD_AQUARIO, A.NOME, A.DESC_ALIMENTO FROM AQUARIO B
JOIN ALIMENTO A ON A.COD_ALIMENTO = B.COD_AQUARIO
WHERE  B.COD_AQUARIO = 1

SELECT * FROM TEMPERATURA ORDER BY HORARIO
SELECT * FROM AQUARIO
SELECT * FROM ALIMENTO

