CREATE TABLE ALIMENTO
(
    COD_ALIMENTO INT NOT NULL IDENTITY(0,1),
    NOME VARCHAR(30) NOT NULL,
    DESC_ALIMENTO VARCHAR(70),
    QUANT_ALIMENTO SMALLINT NOT NULL,
    CONSTRAINT PK_ALIMENTO PRIMARY KEY (COD_ALIMENTO),
);
CREATE TABLE AQUARIO
(
    COD_AQUARIO INT NOT NULL IDENTITY(0,1),
    TEMP_IDEAL SMALLINT NOT NULL,
    PERIODO INT NOT NULL,
    COD_ALIMENTO INT,
    ULTIMO_ALIMENTO DATETIME DEFAULT NULL,
    CONSTRAINT PK_AQUARIO PRIMARY KEY (COD_AQUARIO),
    CONSTRAINT FK_ALIMENTO FOREIGN KEY (COD_ALIMENTO) REFERENCES ALIMENTO(COD_ALIMENTO),
);
CREATE TABLE TEMPERATURA
(
    HORARIO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TEMP INT NOT NULL,
    COD_AQUARIO INT NOT NULL,
    CONSTRAINT FK_AQUARIO FOREIGN KEY (COD_AQUARIO) REFERENCES AQUARIO(COD_AQUARIO),
);


SELECT * FROM ALIMENTO
SELECT * FROM AQUARIO
SELECT * FROM TEMPERATURA


DROP TABLE TEMPERATURA
DROP TABLE AQUARIO
DROP TABLE ALIMENTO
